baseurl = "/"
languageCode = "en-us"
title = "networkconnor.com"
canonifyurls = true

[permalinks]
post = "/:year/:month/:day/:filename/"
[params]
author = "networkconnor"
subtitle = "networkconnor's archive of information"
description = ""
twitter_url = ""
github_url = ""
copyright_since = "2021"
copyright_latest = "2021"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
	  unsafe = true
